export const COMMON_PROGRAMMING_LANGUAGES_EXTENSIONS: {
    [key: string]: string;
} = {
    "ts": "typescript",
    "js": "javascript",
    "py": "python",
    "java": "java",
    "c": "c",
    "cpp": "cpp",
    "cs": "csharp",
    "go": "go",
    "php": "php",
    "rb": "ruby",
    "rs": "rust",
    "swift": "swift",
    "kt": "kotlin",
    "scala": "scala",
    "pl": "perl",
    "r": "r",
    "dart": "dart",
    "hs": "haskell",
    "lisp": "lisp",
    "lua": "lua",
    "ml": "ocaml",
    "html": "html",
    "json": "json",
    "css": "css",
    "xml": "xml",
    "yml": "yaml",
    "sh": "bash",
    "sql": "sql",
    "dockerfile": "dockerfile",
    "md": "markdown",
    "txt": "text",
    "svg": "svg",
    "vue": "vue",
    "jsx": "jsx",
    "tsx": "tsx",
    "handlebars": "handlebars",
    "hbs": "handlebars",
    "ejs": "ejs",
    "pug": "pug",
    "jade": "pug",
    "coffee": "coffeescript",
    "csx": "coffeescript",
    "less": "less",
    "scss": "scss",
}